[project]
name = "flowptr-client"
version = "0.1.0"
description = "httpx client for FlowPTR REST API"
readme = "README.md"
requires-python = "==3.9.*"
dependencies = [
    "authlib>=1.6.0",
    "httpx>=0.28.0",
    "pydantic>=2.11.0",
    "pydantic-settings>=2.7.0",
    "rich>=14.0.0",
]

# Define where the package is located
[tool.hatch.build.targets.wheel]
packages = ["src/flowptr_client"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "bpython>=0.24",
    "openapi-python-client>=0.25.0",
    "pre-commit>=4.2.0",
    "pytest-asyncio>=0.25.0",
    "pytest-env>=1.1.5",
    "pytest-httpx>=0.35.0",
    "pytest>=8.3.4",
    "respx>=0.21.1",
    "ruff>=0.8.3",
]

[tool.ruff]
include = ["src/flowptr_client/**/*.py"]
target-version = "py39"
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = [
    "ERA", # Commented out code
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "G", # flake8-logging-format
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "ARG", # unused arguments in functions
]
ignore = [
    "B008",  # do not perform function calls in argument defaults
    "B904",  # Allow raising exceptions without from e, for HTTPException
]
[tool.ruff.lint.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
# https://github.com/astral-sh/ruff/issues/6740
keep-runtime-typing = true

[tool.pytest.ini_options]
addopts = "-vv --cov=src/flowptr_client --cov-branch --cov-report=term-missing --cov-report xml:coverage.xml --junitxml=report.xml tests/"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
    "ignore::ImportWarning",
    "ignore::UserWarning",
    "ignore::FutureWarning",
]
