[pytest]
required_plugins = pytest-env
env =
    FPT_CLIENT_ID=test_client
    FPT_CLIENT_SECRET=test_secret
    FPT_DOMAIN=https://test.shotgunstudio.com/
    FPT_TOKEN_ENDPOINT=api/v1/auth/access_token
    FPT_API_VERSION=api/v1